version: '3.8'

services:
# En docker-compose.yml
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #volumes:
    #postgres-data:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - reservation-net

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - reservation-net

  processing-service:
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - reservation-net

networks:
  reservation-net:
    driver: bridge